Another error occurs:
ERROR:  insert or update on table "loanlist" violates foreign key constraint "loanlist_isbn_fkey1"
            DETAIL:  Key (isbn,copy_id)=(0375842209,3) is not present in table "copies".

This means that I need to either add that extra copy of the book to the Copies table OR not include that in the LoanList table.